"use client";

import { FontAwesomeIcon, type FontAwesomeIconProps } from "@fortawesome/react-fontawesome";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowLeftLong,
  faArrowRightLong,
  faArrowsRotate,
  faArrowRotateLeft,
  faBars,
  faBolt,
  faBoxOpen,
  faCartShopping,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleUser,
  faClipboardList,
  faClockRotateLeft,
  faCreditCard,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFire,
  faGaugeHigh,
  faGift,
  faHandHoldingDollar,
  faHeadset,
  faHeart,
  faHouse,
  faLeaf,
  faLocationDot,
  faLock,
  faMagicWandSparkles,
  faMagnifyingGlass,
  faMinus,
  faMobileScreenButton,
  faPhone,
  faPlus,
  faRepeat,
  faRightFromBracket,
  faRotateRight,
  faShieldHalved,
  faSliders,
  faSpinner,
  faStar,
  faStarHalfStroke,
  faSun,
  faTag,
  faTrashCan,
  faTruckFast,
  faUser,
  faWallet,
  faXmark,
  faMoon,
} from "@fortawesome/free-solid-svg-icons";
import {
  faEye as faEyeFar,
  faHeart as faHeartFar,
  faStar as faStarFar,
  faUser as faUserFar,
} from "@fortawesome/free-regular-svg-icons";
import {
  faApple,
  faCcMastercard,
  faCcVisa,
  faFacebookF,
  faGoogle,
  faInstagram,
  faLinkedin,
  faPaypal,
  faTwitter,
  faYoutube,
} from "@fortawesome/free-brands-svg-icons";

export const icons = {
  "truck": faTruckFast,
  "gift": faGift,
  "headset": faHeadset,
  "shield": faShieldHalved,
  "box-open": faBoxOpen,
  "search": faMagnifyingGlass,
  "cart": faCartShopping,
  "menu": faBars,
  "close": faXmark,
  "chevron-down": faChevronDown,
  "chevron-right": faChevronRight,
  "chevron-left": faChevronLeft,
  "home": faHouse,
  "card": faCreditCard,
  "star": faStar,
  "star-half": faStarHalfStroke,
  "star-far": faStarFar,
  "minus": faMinus,
  "plus": faPlus,
  "eye": faEye,
  "eye-far": faEyeFar,
  "eye-slash": faEyeSlash,
  "rotate": faArrowsRotate,
  "rotate-left": faArrowRotateLeft,
  "refresh": faRotateRight,
  "repeat": faRepeat,
  "phone": faPhone,
  "mail": faEnvelope,
  "pin": faLocationDot,
  "user": faUser,
  "user-far": faUserFar,
  "user-circle": faCircleUser,
  "check-circle": faCircleCheck,
  "sliders": faSliders,
  "sparkles": faMagicWandSparkles,
  "fire": faFire,
  "bolt": faBolt,
  "leaf": faLeaf,
  "tag": faTag,
  "hand-dollar": faHandHoldingDollar,
  "mobile": faMobileScreenButton,
  "arrow-left": faArrowLeftLong,
  "arrow-right": faArrowRightLong,
  "trash": faTrashCan,
  "heart": faHeart,
  "heart-far": faHeartFar,
  "lock": faLock,
  "signout": faRightFromBracket,
  "wallet": faWallet,
  "orders": faClipboardList,
  "history": faClockRotateLeft,
  "account": faCircleUser,
  "gauge": faGaugeHigh,
  "facebook": faFacebookF,
  "google": faGoogle,
  "apple": faApple,
  "instagram": faInstagram,
  "twitter": faTwitter,
  "youtube": faYoutube,
  "linkedin": faLinkedin,
  "visa": faCcVisa,
  "mastercard": faCcMastercard,
  "paypal": faPaypal,
  "sun": faSun,
  "moon": faMoon,
} as const;

export type IconName = keyof typeof icons;

const spinner = faSpinner;

export function Ico({
  name,
  className,
  style,
  spin,
}: {
  name: IconName | "spinner";
  className?: string;
  style?: FontAwesomeIconProps["style"];
  spin?: boolean;
}) {
  const def: IconDefinition = name === "spinner" ? spinner : icons[name];
  return <FontAwesomeIcon icon={def} className={className} style={style} spin={spin} />;
}

export default Ico;